name: 文韬·秘
markdown: kramdown
paginate: 5
paginate_path: "page/:num"
plugins: [jekyll-paginate,jekyll-feed]
seurl: /
url: http://blog.wentao.me
title: 文韬·秘
description: 文韬的blog
sass:
  sass_dir: _scss 
  style: compressed